### ISSUE TITLE
Feature Idea

### ISSUE THREAD

**Issue by tb102122** [Booligoosh/covid19nsw#6]
Hey Ethan,

first of all great website. Gives a nice and quick overview!
Would it be possible to add overview of the total numbers and vaccination rate in NSW.
With the latest announcement it the restriction lifting it be be of much interest of the people.
I am unfortunately not a VUE developer otherwise I would have submitted a PR for it. ;-)

Cheers Tobias

**Comment by Booligoosh** [comment]
Hey Tobias! How does something like this look?

<img width="1435" alt="Screen Shot 2021-09-09 at 1 25 06 pm" src="https://user-images.githubusercontent.com/14034891/132617455-df846c5f-ea77-4f93-ae29-e9119db591f0.png">

**Comment by tb102122** [comment]
Great! 
Maybe just a small headline to show that it is the NSW total.

**Comment by tb102122** [comment]
Or just like the charts per counsel that people see a full trend as well.

**Comment by Booligoosh** [comment]
Added a box to the vaccinations pages with the headline!
https://covid19nsw.ethan.link/vaccines/by-postcode
https://covid19nsw.ethan.link/vaccines/by-council

<img width="1440" alt="Screen Shot 2021-09-09 at 7 51 49 pm" src="https://user-images.githubusercontent.com/14034891/132664556-5e383135-3f7c-4c20-9499-8cf214df797d.png">
